#!/bin/sh

export SIMPLEAPI_SERVER_PORT="8080"

export SIMPLEAPI_DB_HOST="172.17.0.2"
export SIMPLEAPI_DB_PORT="3306"
export SIMPLEAPI_DB_USER="root"
export SIMPLEAPI_DB_PASSWORD="mypass"

exec ./target/simple-api
