#!/bin/sh

export SIMPLEAPI_SERVER_PORT="8888"

export SIMPLEAPI_DB_URL="localhost"
export SIMPLEAPI_DB_PORT="3333"
export SIMPLEAPI_DB_USER="admin"
export SIMPLEAPI_DB_PASSWORD="1q2w3e"

exec ./target/simple-api
