#!/bin/sh

# Server settings
export SIMPLEAPI_SERVER_PORT="8080"
                                                                                                                                                                                                                                                                               
# DB Connection string
#export SIMPLEAPI_DB_HOST="172.17.0.3"                                                                                                                                                                                                                                         
#export SIMPLEAPI_DB_PORT="3306"
#export SIMPLEAPI_DB_USER="root"
#export SIMPLEAPI_DB_PASSWORD="mypass"
export SIMPLEAPI_DB_HOST="localhost"
export SIMPLEAPI_DB_PORT="3306"
export SIMPLEAPI_DB_USER="simple-api"
export SIMPLEAPI_DB_PASSWORD="7pMkMc7CNG"

# DB parameters
#export SIMPLEAPI_SKIP_CREATE_DB="false"
#export SIMPLEAPI_SKIP_CREATE_TABLES="false"
export SIMPLEAPI_SKIP_CREATE_DB="true"
export SIMPLEAPI_SKIP_CREATE_TABLES="true"

exec ./target/simple-api
