#!/bin/sh

API_URL=http://localhost:8080

curl -k -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' --header "Authorization: bearer ${API_TOKEN}"  $API_URL/api/config

